### ISSUE TITLE
Can I use biostar160470.jar with a psi-tBLASTn checkpint file as query?

### ISSUE THREAD

**Issue by carina-paola** [lindenb/jvarkit#135]
Hello,

I am running psi-tBLASTn and I generated a checkpoint file (.chk) which is a Position Specific Scoring Matrix (PSSM). I want to know if it is possible to use biostar160470.jar to get the hit DNA sequences when I use the  checkpoin file as query in tBLASTn. 

The current command for psi-tBLASTn: 

`tblastn -num_threads 20 -db blastdb_P_bachei -in_pssm A_thaliana_mMit_psiblast_10it.chk -outfmt 6 -out test_P_bachei_tblastn.out`

If it's not possible, I would really appreciate if someone could tell me another way to get them, or if I am wrong assuming I need to get Bidirectional Best Hits in psi-tBLASTn to validate the results (I am new at this).

Thank you!

Paola

**Comment by lindenb** [comment]
>  I want to know if it is possible to use biostar160470.jar

No idea.
did you try it ?

**Comment by carina-paola** [comment]
Yes, I tried the next command:

`cat A_thaliana_mMit_psiblast_10it.chk | /space31/PEG/pcornejo/ncbi-blast-2.3.0+/bin/tblastn -num_threads 20 -db blastdb_P_bachei -outfmt 5 | java -jar /space31/PEG/pcornejo/jvarkit/dist/biostar160470.jar -p /space31/PEG/pcornejo/ncbi-blast-2.3.0+/bin/ -d blastdb_P_bachei  | xmllint --format - > test_P_bachei_tblastn_F5.out`

but I got a lot of parsing errors (the PSSM is huge). 
I just tried the following:

`/space31/PEG/pcornejo/ncbi-blast-2.3.0+/bin/tblastn -num_threads 20 -db blastdb_P_bachei -in_pssm A_thaliana_mMit_psiblast_10it.chk -outfmt 5 | java -jar /space31/PEG/pcornejo/jvarkit/dist/biostar160470.jar -p /space31/PEG/pcornejo/ncbi-blast-2.3.0+/bin/ -d blastdb_P_bachei  | xmllint --format - > test_P_bachei_tblastn_F5.out`

And it seems it is not possible:

[SEVERE][Biostar160470]only tblastn is supported but got : psitblastn
java.io.IOException: only tblastn is supported but got : psitblastn
	at com.github.lindenb.jvarkit.tools.biostar.Biostar160470.parseBlast(Biostar160470.java:181)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar160470.doWork(Biostar160470.java:336)
	at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMain(Launcher.java:756)
	at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMainWithExit(Launcher.java:919)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar160470.main(Biostar160470.java:358)
[INFO][Launcher]biostar160470 Exited with failure (-1)
-:2: parser error : Premature end of data in tag BlastOutput line 1

Thank you anyway.
