### ISSUE TITLE
install error ? 

### ISSUE THREAD

**Issue by hmyh1202** [lindenb/jvarkit#138]
git clone you code of github and run:
./gradlew vcfin

**Exception in thread "main" java.io.IOException: Input/output error
        at sun.nio.ch.FileDispatcherImpl.lock0(Native Method)
        at sun.nio.ch.FileDispatcherImpl.lock(FileDispatcherImpl.java:89)
        at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1024)
        at java.nio.channels.FileChannel.tryLock(FileChannel.java:1154)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:55)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:62)**

My java is jdk-11.0.1

**Comment by lindenb** [comment]
I've just fixed a problem with the 'tests' but the gradle issue above is more related to your OS and your filesystem: https://www.google.com/search?q=.FileChannelImpl.tryLock+ioexception&ie=utf-8&oe=utf-8

**Comment by lindenb** [comment]
furthermore, i was able to compile it with openjdk12

**Comment by hmyh1202** [comment]
However can compile some usefull tools that suit for such as centOS et al., linux system ?
