### ISSUE TITLE
ERROR IN VCF HEADER

### ISSUE THREAD

**Issue by AqsaMajeed-star** [lindenb/jvarkit#141]
### Verify
* openjdk version "11.0.5" 
OpenJDK Runtime Environment (build 11.0.5)
OpenJDK 64-Bit Server VM (build 11.0.5, mixed mode, sharing)

### Subject of the issue
I ran bcftools merge tool for five of vcfs for which variants were called using samtools. The merged_vcf was used as input for FixVcfMissingGenotypes. Unfortunately, the scripts fails after a few seconds and outputs the following error: "htsjdk.tribble.TribbleException$InvalidHeader: Your input file has a malformed header: We never saw the required CHROM header line (starting with one #) for the input VCF file"

### Your environment
* which OS : linux-gnu

Error Message

[SEVERE][Launcher]Your input file has a malformed header: We never saw the required CHROM header line (starting with one #) for the input VCF file
htsjdk.tribble.TribbleException$InvalidHeader: Your input file has a malformed header: We never saw the required CHROM header line (starting with one #) for the input VCF file
	at htsjdk.variant.vcf.VCFCodec.readActualHeader(VCFCodec.java:115)
	at htsjdk.variant.vcf.VCFIteratorBuilder$VCFReaderIterator.<init>(VCFIteratorBuilder.java:177)
	at htsjdk.variant.vcf.VCFIteratorBuilder.open(VCFIteratorBuilder.java:97)
	at com.github.lindenb.jvarkit.util.vcf.VCFUtils.createVCFIteratorFromInputStream(VCFUtils.java:288)
	at com.github.lindenb.jvarkit.util.vcf.VCFUtils.createVCFIterator(VCFUtils.java:326)
	at com.github.lindenb.jvarkit.util.jcommander.Launcher.openVCFIterator(Launcher.java:515)
	at com.github.lindenb.jvarkit.util.jcommander.Launcher.doVcfToVcf(Launcher.java:565)
	at com.github.lindenb.jvarkit.util.jcommander.Launcher.doVcfToVcf(Launcher.java:614)
	at com.github.lindenb.jvarkit.tools.misc.FixVcfMissingGenotypes.doWork(FixVcfMissingGenotypes.java:346)
	at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMain(Launcher.java:777)
	at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMainWithExit(Launcher.java:940)
	at com.github.lindenb.jvarkit.tools.misc.FixVcfMissingGenotypes.main(FixVcfMissingGenotypes.java:358)
[INFO][Launcher]fixvcfmissinggenotypes Exited with failure (-1)

**Comment by lindenb** [comment]
what is the output of 
`
file your.vcf
`
and 

`grep "#CHROM" your.vcf
`
