### ISSUE TITLE
error when running the packages

### ISSUE THREAD

**Issue by tatianaalmeida** [lindenb/jvarkit#15]
Hi, I'm really new at this, and I'm probably doing something stupid but I don't have anyone to ask
I'm trying to use vcfgo and I manage to install the jvarkit with ant, after I run ant vcfgo it says  build successful, but when I try to run the test of vcfgo 

java -jar dist/vcfgo.jar ../snpEff/file.eff.vcf ../snpEff/file_go.vcf

I keep getting this:

Exception in thread "main" java.lang.NoClassDefFoundError: htsjdk/variant/vcf/VCFHeaderLine
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2442)
	at java.lang.Class.getMethod0(Class.java:2685)
	at java.lang.Class.getMethod(Class.java:1620)
	at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:492)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:484)
Caused by: java.lang.ClassNotFoundException: htsjdk.variant.vcf.VCFHeaderLine
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	... 6 more

I tried to run other things in the jvarkit and the same error keeps appearing

I'm using the terminal in a MacBook Pro 2009 runing OS X Mavericks 10.9.5 with 8Gb RAM, The Java is the 7, and I got the ant apache installed with Homebrew.

Can you help me please?

**Comment by alunem** [comment]
Hi Pierre,
I try to use your kg2bed program as seen on Biostars, and I'm encountering a very similar problem as Tatiana. My environment is CentOS 6.7.
Please find the outputs of the java execution below: 
``` 
$ curl -s "http://hgdownload.cse.ucsc.edu/goldenPath/hg19/database/knownGene.txt.gz" |  gunzip -c |  java -jar dist/kg2bed.jar 
[INFO/KnownGenesToBed] 2015-09-14 15:34:37 "Starting JOB at Mon Sep 14 15:34:37 CEST 2015 com.github.lindenb.jvarkit.tools.misc.KnownGenesToBed version=b1ddf8ca859f85caec9c29b4ee62f2364b56902f  built=2015-09-10:18-09-31"
[INFO/KnownGenesToBed] 2015-09-14 15:34:37 "Command Line args : (EMPTY/NO-ARGS)"
[INFO/KnownGenesToBed] 2015-09-14 15:34:37 "Executing as emmanuel@host on Linux 2.6.32-573.3.1.el6.x86_64 amd64; OpenJDK 64-Bit Server VM 1.7.0_85-mockbuild_2015_07_25_13_10-b00"
[INFO/KnownGenesToBed] 2015-09-14 15:34:37 "Reading from stdin"
Exception in thread "main" java.lang.NoClassDefFoundError: htsjdk/tribble/readers/LineIterator
        at com.github.lindenb.jvarkit.tools.misc.KnownGenesToBed.doWork(KnownGenesToBed.java:141)
        at com.github.lindenb.jvarkit.util.AbstractCommandLineProgram.instanceMain(AbstractCommandLineProgram.java:500)
        at com.github.lindenb.jvarkit.util.AbstractCommandLineProgram.instanceMainWithExit(AbstractCommandLineProgram.java:514)
        at com.github.lindenb.jvarkit.tools.misc.KnownGenesToBed.main(KnownGenesToBed.java:172)
Caused by: java.lang.ClassNotFoundException: htsjdk.tribble.readers.LineIterator
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 4 more
```
I believe that htsjdk compilation worked fine:
```
# ant htsjdk-jar
Buildfile: build.xml

write-version-property:
[propertyfile] Updating property file: /opt/jvarkit/htsjdk/htsjdk.version.properties

init:

compile-samtools:

compile-tribble:

compile-variant:

htsjdk-jar:

BUILD SUCCESSFUL
Total time: 2 seconds

```

And here is the output of the find command:
```
]$ find ./ -type f -name "*.jar" -o -name "htsjdk.ve*" 
./dist/vcffilterjs.jar
./dist/kg2bed.jar
./htsjdk/dist/apache-ant-1.8.2-bzip2.jar
./htsjdk/dist/htsjdk-1.133.jar
./htsjdk/dist/snappy-java-1.0.3-rc3.jar
./htsjdk/dist/commons-jexl-2.1.1.jar
./htsjdk/dist/commons-compress-1.4.1.jar
./htsjdk/dist/commons-logging-1.1.1.jar
./htsjdk/dist/xz-1.5.jar
./htsjdk/lib/apache-ant-1.8.2-bzip2.jar
./htsjdk/lib/snappy-java-1.0.3-rc3.jar
./htsjdk/lib/commons-jexl-2.1.1.jar
./htsjdk/lib/testng/testng-5.5-jdk15.jar
./htsjdk/lib/commons-compress-1.4.1.jar
./htsjdk/lib/commons-logging-1.1.1.jar
./htsjdk/lib/xz-1.5.jar
./htsjdk/htsjdk.version.properties
```
Have you got any clue? 
Thanks Pierre

**Comment by lindenb** [comment]
This is not the right way to compile kg2bed ; https://github.com/lindenb/jvarkit/wiki/KnownGenesToBed

```
 make kg2bed
```

**Comment by alunem** [comment]
Sorry I forgot to mention I followed those instructions first (with a "BUILD SUCCESSFUL" as a result), and, after seeing the error was related to htsjdk, I tried to build it separately.
I've just made a `make kg2bed` in order to check again, and this does not change the error message.

**Comment by lindenb** [comment]
please, show me the output of 
```
$ java -version && java -jar dist/kg2bed.jar -h
```

**Comment by alunem** [comment]
Here it is:
```
java -version 
java version "1.7.0_85"
OpenJDK Runtime Environment (rhel-2.6.1.3.el6_7-x86_64 u85-b01)
OpenJDK 64-Bit Server VM (build 24.85-b03, mixed mode)
```

```
# java -jar dist/kg2bed.jar -h
[INFO/KnownGenesToBed] 2015-09-14 16:08:46 "Starting JOB at Mon Sep 14 16:08:46 CEST 2015 com.github.lindenb.jvarkit.tools.misc.KnownGenesToBed version=b1ddf8ca859f85caec9c29b4ee62f2364b56902f  built=2015-09-10:18-09-31"
[INFO/KnownGenesToBed] 2015-09-14 16:08:46 "Command Line args : -h"
[INFO/KnownGenesToBed] 2015-09-14 16:08:46 "Executing as root@host on Linux 2.6.32-573.3.1.el6.x86_64 amd64; OpenJDK 64-Bit Server VM 1.7.0_85-mockbuild_2015_07_25_13_10-b00"

KnownGenesToBed
===============

Description: KnownGene to BED.

Author         : Pierre Lindenbaum PhD.
Mail           : plindenbaum@yahoo.fr
WWW            : https://github.com/lindenb/jvarkit/wiki/KnownGenesToBed
Compilation    : 2015-09-10:18-09-31
Git-Hash       : b1ddf8ca859f85caec9c29b4ee62f2364b56902f
Htsjdk-version : 1.133
Htsjdk-home    : /root/Downloads/jvarkit/htsjdk-1.133

Usage:
	java -cp jar1.jar:jar2.jar:jar3.jar com.github.lindenb.jvarkit.tools.misc.KnownGenesToBed [options] (files)

Options:
 -i don't print introns
 -u don't print utr
 -c don't print cds
 -x don't print exons
 -t don't print transcripts
 -h get help (this screen)
 -v print version and exit.
 -L (level) log level. One of java.util.logging.Level . currently:null
Exception in thread "main" java.lang.NoClassDefFoundError: htsjdk/samtools/util/CloserUtil
	at com.github.lindenb.jvarkit.util.AbstractCommandLineProgram.isGalaxyTool(AbstractCommandLineProgram.java:533)
	at com.github.lindenb.jvarkit.util.AbstractCommandLineProgram.printOptions(AbstractCommandLineProgram.java:352)
	at com.github.lindenb.jvarkit.tools.misc.KnownGenesToBed.printOptions(KnownGenesToBed.java:106)
	at com.github.lindenb.jvarkit.util.AbstractCommandLineProgram.printUsage(AbstractCommandLineProgram.java:245)
	at com.github.lindenb.jvarkit.util.AbstractCommandLineProgram.printUsage(AbstractCommandLineProgram.java:251)
	at com.github.lindenb.jvarkit.util.AbstractCommandLineProgram.handleOtherOptions(AbstractCommandLineProgram.java:365)
	at com.github.lindenb.jvarkit.tools.misc.KnownGenesToBed.doWork(KnownGenesToBed.java:125)
	at com.github.lindenb.jvarkit.util.AbstractCommandLineProgram.instanceMain(AbstractCommandLineProgram.java:500)
	at com.github.lindenb.jvarkit.util.AbstractCommandLineProgram.instanceMainWithExit(AbstractCommandLineProgram.java:514)
	at com.github.lindenb.jvarkit.tools.misc.KnownGenesToBed.main(KnownGenesToBed.java:172)
Caused by: java.lang.ClassNotFoundException: htsjdk.samtools.util.CloserUtil
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 10 more
```

**Comment by lindenb** [comment]
hum... I'm puzzled... can you please show the output of
```
$ jar xvf dist-1.133/kg2bed.jar   META-INF/MANIFEST.MF && cat META-INF/MANIFEST.MF
```

by the way, you should never install/run this kind of program as root....

**Comment by alunem** [comment]
Here is:
```
# jar xvf dist-1.133/kg2bed.jar   META-INF/MANIFEST.MF && cat META-INF/MANIFEST.MF
 inflated: META-INF/MANIFEST.MF
Manifest-Version: 1.0
Git-Hash: b1ddf8ca859f85caec9c29b4ee62f2364b56902f
Class-Path: /opt/jvarkit/htsjdk-1.133/dist/commons-jexl-2.1.1.jar /opt
 /jvarkit/htsjdk-1.133/dist/commons-logging-1.1.1.jar /opt/jvarkit/hts
 jdk-1.133/dist/htsjdk-1.133.jar /opt/jvarkit/htsjdk-1.133/dist/snappy
 -java-1.0.3-rc3.jar /opt/jvarkit/dist-1.133/kg2bed.jar
Compile-Date: 2015-09-14:15-09-32
Created-By: 1.7.0_85 (Oracle Corporation)
Main-Class: com.github.lindenb.jvarkit.tools.misc.KnownGenesToBed
```
Everything was done in my home as a simple user before I moved the folder to /opt/
And since, indeed, I tried some debug as a root and I know it's bad ;-)

**Comment by lindenb** [comment]
```
 before I moved the folder to /opt/
```
don't move things. Recompile where the tool should be installed.

**Comment by alunem** [comment]
So I made a fresh install, I did not move or copy anything to be run from elsewhere and...
it worked !!

Thanks Pierre for your help.

PS: what is your recommendation if I want the tool to be installed once for several users ?

**Comment by lindenb** [comment]
compile it into a shared place.
something like:
```
/usr/local/jvarkit
```

**Comment by kevinblighe** [comment]
Hey Pierre / Tatiana,

I just came across the same problem as Tatiana but I was able to fix it by moving the contents of
_htsjdk/build/classes/main/htsjdk/_ (which included directories called samtools, variant, and tribble, containing compiled class files) into _htsjdk/_

I then compile with `javac -cp htsjdk/build/libs/htsjdk-2.12.0-8-gd8e037a-SNAPSHOT.jar *.java` and import with `import htsjdk.samtools.* ;`

My build for htsjdk was successful.
