### ISSUE TITLE
sam2tsv doesn't report chrX, Y, M reads

### ISSUE THREAD

**Issue by kac2053** [lindenb/jvarkit#166]
### Subject of the issue
sam2tsv doesn't report chrX, Y, M reads

### Your environment
* version of jvarkit
```
$java -jar dist/sam2tsv.jar --version
2b40bcc06
```
(It doesn't look like a proper version number, but I am not trained in bioinformatics/computation so sorry if I report technical things that have obvious solutions.)

* version of java
```
$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

```
* the value of `${JAVA_HOME}`
```
${JAVA_HOME}
-bash: /opt/common/CentOS_7/java/jdk1.8.0_131: Is a directory
```

* which OS
```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### Steps to reproduce
In order to reproduce, I would need to provide our bam file and we do not want to release the data before publishing.

### Expected behaviour
I expect sam2tsv to report reads for all chromosomes, but chrX, chrY, and chrM are missing in the output despite high quality reads mapping there when I check in IGV.

### Actual behaviour
sam2tsv does not report reads at X, Y, and M. Is there a reason why?
(It reports chr 1 - 19 only.)

My command if this helps:
`java -jar dist/sam2tsv.jar -R GRCm38_dna_primary_assembly/Mus_musculus.GRCm38.dna.primary_assembly_corrected_chr_annotation.fa Sample_A.bam > Sample_A_sam2tsv.txt`

Again, sorry if my question seems stupid. I am from wet-lab background. Thank you.

**Comment by lindenb** [comment]
thanks for the report. Please what is the output of `samtools idxstats  Sample_A.bam'  please ?

**Comment by lindenb** [comment]
ah, and please, can you please show me the output of:

`samtools view Sample_A.bam chrX | head`

**Comment by kac2053** [comment]
Thank you for such a quick reply.

```
chr1	195471971	87985	0
chr10	130694993	55648	0
chr11	122082543	391779	0
chr12	120129022	48624	0
chr13	120421639	93805	0
chr14	124902244	49403	0
chr15	104043685	64831	0
chr16	98207768	70138	0
chr17	94987271	283215	0
chr18	90702639	56252	0
chr19	61431566	46529	0
chr2	182113224	89303	0
chr3	160039680	64756	0
chr4	156508116	71114	0
chr5	151834684	88958	0
chr6	149736546	75237	0
chr7	145441459	89827	0
chr8	129401213	64240	0
chr9	124595110	84755	0
chrM	16299	49865	0
chrX	171031299	39657	0
chrY	91744698	1288	0
JH584299.1	953012	2	0
GL456233.1	336933	103	0
JH584301.1	259875	0	0
GL456211.1	241735	5	0
GL456350.1	227966	33	0
JH584293.1	207968	13	0
GL456221.1	206961	2	0
JH584297.1	205776	0	0
JH584296.1	199368	0	0
GL456354.1	195993	0	0
JH584294.1	191905	2	0
JH584298.1	184189	0	0
JH584300.1	182347	0	0
GL456219.1	175968	0	0
GL456210.1	169725	4	0
JH584303.1	158099	0	0
JH584302.1	155838	0	0
GL456212.1	153618	1	0
JH584304.1	114452	810	0
GL456379.1	72385	1	0
GL456216.1	66673	28	0
GL456393.1	55711	0	0
GL456366.1	47073	1	0
GL456367.1	42057	0	0
GL456239.1	40056	0	0
GL456213.1	39340	0	0
GL456383.1	38659	1	0
GL456385.1	35240	0	0
GL456360.1	31704	0	0
GL456378.1	31602	1	0
GL456389.1	28772	1	0
GL456372.1	28664	0	0
GL456370.1	26764	11	0
GL456381.1	25871	0	0
GL456387.1	24685	0	0
GL456390.1	24668	0	0
GL456394.1	24323	0	0
GL456392.1	23629	5	0
GL456382.1	23158	1381	0
GL456359.1	22974	2	0
GL456396.1	21240	1	0
GL456368.1	20208	1	0
JH584292.1	14945	0	0
JH584295.1	1976	49	0
*	0	0	0
```


```
$ samtools view Sample_A.bam chrX | head
3cfe3b25-3608-4966-8b92-4dda119628ff	0	chrX	3823975	1	62S37M2I38M2D2M1D23M4D6M1D23M1D8M1D19M1D7M1I57M1D16M1D10M1D3M1D15M1I15M1I4M1I11M1D14M1I8M1I15M1D20M1I21M1I3M1I13M2I7M1D35M2D30M1D3M1I29M7D4M2I3M4I16M2I36M4D9M2D9M1I2M3I10M1I46M1D12M2D33M1I28M1D38M1D7M1D13M4I48M1D59M1D22M1I27M1D30M1D31M1D9M1D29M3D24M1I76M1I65M1I16M3D8M1I7M2D8M1D55M1D15M1D9M1D7M14S	*	0	0	GTTATGCTTCGTTCGGTACGTATTGCTAAGCAGTGGTATCAACACCAGTACATGGGAGCACACCACTTCGCCCAGGTCAGGAACCCCCAACACACCTGAGGGAGCCTAGACCTAGATTTAAAAGCATATCTCATGATGAGTGAGGACGCCAAGAAGGACTGTCATCACTTAAGAAATACAGGAGAACACTGCTAAGAGTTAAAGTCCTTAAAGAAAAACAGAAAACACAATCAAACAGGTAGAAGTCCTTACAGAAAAAGAGGAAAAAACATACAAACAGGTGATGAAATGAACAAAACCACCTAGACCTAAAAGGAAGTAGACACAATAAAAGAAAACTCAAAGCAGAGAATAACACTGGAATAGAAACCCTAGGAAAAGAAAATCTGGAACCATAGATTTGGCATCAACAACAGAATGCAAAGAGATGGAAGAGAGAATCTCCAGATTGCAGAAAATTCCACATAAAGACATCGGCACAACAATCAAAGAAAATGGAAAATGCAAAGATCCTAACTCAAAATATCCAGGAAATCAGAGACACAATAAGAAGACCAAACGTACGGATGTGGGTAAGACAAAGAATGAAGATTTTCAGCGCTCAAAGGTCCAGCAGGCATCTTCAACAAAGTGTTGAAAGCTTTAAATCTAAAGGAGCCAAGAGATGCCATATGAACATACAAGAAGCCTACAGAACTCCAAATAGACTGGACTAGAAAGAAATTCCTCGACACATAATAATCAGAACATCAAATGCACTAGACTAAAGATAGAATACTAAAAGCAGTAAGGAAAAAGGTCAAGTAACATATAAAGGCAAACCTATCAAATTACACAGATTTTTCACCAGAGAGAGACTATGAAAGCCAGAGAAGCCTGGACAGATGTTATACAGACACTAGAGAACACAAACTGCAGCCCAGGCTACTATGCCCAGCCAAACTCTCAATTATCATAGAGGAGAAACCAAAGTATTCCACGAACAAAACCAAATTCACGCATTATCTCTCACGAATCCAGCCCTTCAAAGGATAATAACGAAAAAAACCAATACAAGAACAGGAACAACGCCTAGAAAAACAAGAAGGTAATCCCTCAACAAACCTAAAAGACAGCCACAAGAACAGAATGCACACCTTTAACAACTAAAATAACAGGAAGCAACAATTACTTTTCCTTAATATCTCTTAACATCAATGGTCTCAATTCTACCAATAAAAAGACATGAACTAACTCATTGGCTACACAAACAAGACCCAACATTTTGCTGCTTACAGGGAAACTCATCTCAGAAAAGATAGGCCTCTATCAGAATGAAGGCTGGAAAACAATTTTCAAGCAAATGGTATGAAGAAACAAGCAGGAGTAGCCTCCTAATATCTGATAAATTGACTTCAACCCATGTACTCTGCGTTG	'%%+--**-.9A<9'&/'/144::;@:B9/++-88562)=?+%%$%'&%%''%&**,)(++032(,-/.1222**(&/$)-&,'(''&2-555444313$.*,(23636<9:849)7@AJE0**0,>A==;9621+'''+**(756##$$89380:9/)3168--80444A=&-/5...3>8>58=9739<;?=:0(:(1:9<88:<==IE?055<8146671:507<<E?CGE1.-/-&&%./166:8708=>J=600.$*=.-67?=9,%%%%?4,;7?65674*,$()*08;</*$%%#$.337459CH9))/,2-222=;>@HHAB:6('B>HB><80+5,&&%&&&%%2//0&$'(,,///7=<;=@7355@8++%*/:0*8(-+',&&/'(,-:<88%444;4')5+02$$(&&),,+?57E:;.,A>1-1-000)-%2(*)--*00/8/+(*='/%*(&''((23;79'*.2:79=A3*?K=582/CD99632@C75296126&&/8;;21@?@F>::%%;/'$;?2-5(&$*(''&&4BDE2305@CDJHA./(*3-27$$%&(*$$%('##&&'((((+,**;<=::7&%&34DD>=,7%%3/###$%&%23%.*%$$%1$(%#'(+&+(&%%%$#.>:>;?><-)*(&%''&,./31()'%&,//877563,8'+/,78899?<6:>B%961.233B?C>7.%#%'51,120-:<13(-.3.2(:=ACEH@8C574:;>;F>GB00.150,)+(,0>4<B=>426>,#/H?.*.,,?ECG<>ED>546;5=B3222..1468:<2('-(9*?=887<84260(%%%%&&;=@CDA0,-54,$=.,4C?B>..-5:267?:5'*)-:<DHE80<;D00<;657899=44)*23447625=BB=?A:7746758;4834,,-$$++*,$%%7717A>5BEA@>:;92+,.'22514<733771.6899),$,(33:BA@200764?*2'$'+.//0'1&0(9+),/222=3-569=<632/9<BBCB/A8%%%/FB@>900E:443470<0((41<2;<?77<<73,2/7+279E97148;;A@AC3/>D;<@D9::?CK6(&;9@:8772*927>;E4492/%%%(()*+*--$$-9?KKP>55%$$'-')&&+)&**(1--9:;>-4..C9449=;>DBH92?;:B=;<;;52<02.//$"##%*65;G:485/-*)'-'*40,./,01'(**+)69;@99:A?/,..1&%%?AFE7--,(0/11-.*&,+)<@A@D;<B<6:2B+2.'')*##&%$&2;<@;A9:8><A@AB>D@=4,-80DC2=/1:GGHH=?8554733'(.3:BA*-,73'*//''%(&(59:5;7=:(7552/0-0*(%&.<8568@74+,114/00/+,$	NM:i:174	ms:i:847	AS:i:847	nn:i:0	ts:A:+	tp:A:P	cm:i:6	s1:i:47	s2:i:56	de:f:0.1033	MD:Z:7A4A0T0C4G0C0A5G6C2A1A8C26^TG2^A6A0T11T1A1^TAAC6^A23^A8^C19^G32A5C25^G16^T0A9^T3^G23A10G0C9^G37^C0A0A2C3G9A6G15A2G7G8G2^A4T30^AA30^C24C7^AATAGGA5T17A8A6A0A13A1T2^TGAA4A4^CC21C26C15C2^A12^CC21A12A13T12^G30G7^G7^C32A0G27^A12T1C16A20C6^T14G23A10^C30^A2T28^C9^T29^AAG26A10A3T2T14C22T14C2C15A0G6A0A1C37C15^AGA5G3A1A3^CC8^A45T2G0A5^A15^C0G8^C7	rl:i:692
```
(There is more in the head of bam file, but I just paste part of it here because it's too long.)

Thank you again!

**Comment by lindenb** [comment]
hum, your first read works on my machine. Do you have enough space on disk ?
what is the output of 

`samtools view -h Sample_A.bam chrX |  java -jar dist/sam2tsv.jar -R GRCm38_dna_primary_assembly/Mus_musculus.GRCm38.dna.primary_assembly_corrected_chr_annotation.fa`

**Comment by kac2053** [comment]
```
#Read-Name	Flag	MAPQ	CHROM	READ-POS0	READ-BASE	READ-QUAL	REF-POS1	REF-BASE	CIGAR-OP
3cfe3b25-3608-4966-8b92-4dda119628ff	0	1	chrX	0	G	'	3823913	T	S
3cfe3b25-3608-4966-8b92-4dda119628ff	0	1	chrX	1	T	%	3823914	A	S
3cfe3b25-3608-4966-8b92-4dda119628ff	0	1	chrX	2	T	%	3823915	A	S
3cfe3b25-3608-4966-8b92-4dda119628ff	0	1	chrX	3	A	+	3823916	A	S
3cfe3b25-3608-4966-8b92-4dda119628ff	0	1	chrX	4	T	-	3823917	C	S
3cfe3b25-3608-4966-8b92-4dda119628ff	0	1	chrX	5	G	-	3823918	G	S
3cfe3b25-3608-4966-8b92-4dda119628ff	0	1	chrX	6	C	*	3823919	T	S
3cfe3b25-3608-4966-8b92-4dda119628ff	0	1	chrX	7	T	*	3823920	A	S
3cfe3b25-3608-4966-8b92-4dda119628ff	0	1	chrX	8	T	-	3823921	G	S
3cfe3b25-3608-4966-8b92-4dda119628ff	0	1	chrX	9	C	.	3823922	G	S
3cfe3b25-3608-4966-8b92-4dda119628ff	0	1	chrX	10	G	9	3823923	A	S
3cfe3b25-3608-4966-8b92-4dda119628ff	0	1	chrX	11	T	A	3823924	A	S
3cfe3b25-3608-4966-8b92-4dda119628ff	0	1	chrX	12	T	<	3823925	T	S
3cfe3b25-3608-4966-8b92-4dda119628ff	0	1	chrX	13	C	9	3823926	C	S
3cfe3b25-3608-4966-8b92-4dda119628ff	0	1	chrX	14	G	'	3823927	T	S
3cfe3b25-3608-4966-8b92-4dda119628ff	0	1	chrX	15	G	&	3823928	T	S
3cfe3b25-3608-4966-8b92-4dda119628ff	0	1	chrX	16	T	/	3823929	A	S
3cfe3b25-3608-4966-8b92-4dda119628ff	0	1	chrX	17	A	'	3823930	C	S
3cfe3b25-3608-4966-8b92-4dda119628ff	0	1	chrX	18	C	/	3823931	T	S
3cfe3b25-3608-4966-8b92-4dda119628ff	0	1	chrX	19	G	1	3823932	A	S
3cfe3b25-3608-4966-8b92-4dda119628ff	0	1	chrX	20	T	4	3823933	A	S
3cfe3b25-3608-4966-8b92-4dda119628ff	0	1	chrX	21	A	4	3823934	C	S
3cfe3b25-3608-4966-8b92-4dda119628ff	0	1	chrX	22	T	:	3823935	A	S
3cfe3b25-3608-4966-8b92-4dda119628ff	0	1	chrX	23	T	:	3823936	G	S
3cfe3b25-3608-4966-8b92-4dda119628ff	0	1	chrX	24	G	;	3823937	G	S
3cfe3b25-3608-4966-8b92-4dda119628ff	0	1	chrX	25	C	@	3823938	A	S
3cfe3b25-3608-4966-8b92-4dda119628ff	0	1	chrX	26	T	:	3823939	A	S
3cfe3b25-3608-4966-8b92-4dda119628ff	0	1	chrX	27	A	B	3823940	C	S
3cfe3b25-3608-4966-8b92-4dda119628ff	0	1	chrX	28	A	9	3823941	T	S
3cfe3b25-3608-4966-8b92-4dda119628ff	0	1	chrX	29	G	/	3823942	A	S
3cfe3b25-3608-4966-8b92-4dda119628ff	0	1	chrX	30	C	+	3823943	A	S
3cfe3b25-3608-4966-8b92-4dda119628ff	0	1	chrX	31	A	+	3823944	G	S
3cfe3b25-3608-4966-8b92-4dda119628ff	0	1	chrX	32	G	-	3823945	A	S
3cfe3b25-3608-4966-8b92-4dda119628ff	0	1	chrX	33	T	8	3823946	C	S
```
The output is longer with more read names than what is pasted here.

**Comment by lindenb** [comment]
ok, I don't think the problems comes from my software, there is no reason it skips any chromosome.
May be something wrong happened (any error message), or you have generated a file that is too big for your quotas ?

**Comment by lindenb** [comment]
another way to test is to run up to the last chrom,  would be:

` java -jar dist/sam2tsv.jar -R GRCm38_dna_primary_assembly/Mus_musculus.GRCm38.dna.primary_assembly_corrected_chr_annotation.fa Sample_A.bam  | tail`

**Comment by kac2053** [comment]
There were no error messages in standard error file after running sam2tsv.
The input bam file is 2.5 GB. I asked for 20 GB and 1 thread when submitting job. The sam2tsv output is 8.6 GB file. Given this information, do you think this was a memory issue? It doesn't seem like the case but I'm not sure.

How would I check for a malformed read in chr19? 

I am running below right now. This might take a while but will paste results when it's done.

`java -jar dist/sam2tsv.jar -R GRCm38_dna_primary_assembly/Mus_musculus.GRCm38.dna.primary_assembly_corrected_chr_annotation.fa Sample_A.bam | tail`

A side question, the "READ-QUAL" column has symbols that I cannot find the corresponding values online.

The symbols in READ-QUAL in my output:
`- , ; : ? . ' " ( ) @ * / & # % + < = > $ 0 1 2 3 4 5 6 7 8 9 A B C D E F G H I J K M N P`

The table I found online to interpret the symbols:
https://support.illumina.com/help/BaseSpace_OLH_009008/Content/Source/Informatics/BS/QualityScoreEncoding_swBS.htm

I don't see J, K, M, N, and P symbols in that table online. It is also not in the old illumina table (https://drive5.com/usearch/manual/quality_score.html).

Our data is Nanopore sequencing so is that why there are more symbols than what is in illumina? What are your thoughts?

Thank you.

**Comment by lindenb** [comment]
> How would I check for a malformed read in chr19?

there would be an error message. May be try to run `picard ValidateSamFile` https://gatk.broadinstitute.org/hc/en-us/articles/360036854731-ValidateSamFile-Picard- on your bam to see any error / warning ( picard use the same API than sam2tsv).

> The symbols in READ-QUAL in my output

I see other symbols in a bam from 1000 genomes.

```
samtools view HG02260.transloc.chr9.14.bam | cut -f 11 | grep . -o | uniq | sort | uniq | tail
E
F
G
H
I
J
K
L
M
N
```

**Comment by kac2053** [comment]
Hi. Here is the output:

```
$ cat stderr.sam2tsv 
[SEVERE][Sam2Tsv]Cannot find contig "chrM" in dictionary:[chr1,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chrMT,chrX,chrY,chrJH584299.1,chrGL456233.1,chrJH584301.1,chrGL456211.1,chrGL456350.1,chrJH584293.1,chrGL456221.1,chrJH584297.1,chrJH584296.1,chrGL456354.1,chrJH584294.1,chrJH584298.1,chrJH584300.1,chrGL456219.1,chrGL456210.1,chrJH584303.1,chrJH584302.1,chrGL456212.1,chrJH584304.1,chrGL456379.1,chrGL456216.1,chrGL456393.1,chrGL456366.1,chrGL456367.1,chrGL456239.1,chrGL456213.1,chrGL456383.1,chrGL456385.1,chrGL456360.1,chrGL456378.1,chrGL456389.1,chrGL456372.1,chrGL456370.1,chrGL456381.1,chrGL456387.1,chrGL456390.1,chrGL456394.1,chrGL456392.1,chrGL456382.1,chrGL456359.1,chrGL456396.1,chrGL456368.1,chrJH584292.1,chrJH584295.1]
com.github.lindenb.jvarkit.lang.JvarkitException$ContigNotFoundInDictionary: Cannot find contig "chrM" in dictionary:[chr1,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chrMT,chrX,chrY,chrJH584299.1,chrGL456233.1,chrJH584301.1,chrGL456211.1,chrGL456350.1,chrJH584293.1,chrGL456221.1,chrJH584297.1,chrJH584296.1,chrGL456354.1,chrJH584294.1,chrJH584298.1,chrJH584300.1,chrGL456219.1,chrGL456210.1,chrJH584303.1,chrJH584302.1,chrGL456212.1,chrJH584304.1,chrGL456379.1,chrGL456216.1,chrGL456393.1,chrGL456366.1,chrGL456367.1,chrGL456239.1,chrGL456213.1,chrGL456383.1,chrGL456385.1,chrGL456360.1,chrGL456378.1,chrGL456389.1,chrGL456372.1,chrGL456370.1,chrGL456381.1,chrGL456387.1,chrGL456390.1,chrGL456394.1,chrGL456392.1,chrGL456382.1,chrGL456359.1,chrGL456396.1,chrGL456368.1,chrJH584292.1,chrJH584295.1]
	at com.github.lindenb.jvarkit.util.picard.GenomicSequence.<init>(GenomicSequence.java:154)
	at com.github.lindenb.jvarkit.tools.sam2tsv.Sam2Tsv.printAln(Sam2Tsv.java:253)
	at com.github.lindenb.jvarkit.tools.sam2tsv.Sam2Tsv.scan(Sam2Tsv.java:382)
	at com.github.lindenb.jvarkit.tools.sam2tsv.Sam2Tsv.doWork(Sam2Tsv.java:443)
	at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMain(Launcher.java:763)
	at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMainWithExit(Launcher.java:926)
	at com.github.lindenb.jvarkit.tools.sam2tsv.Sam2Tsv.main(Sam2Tsv.java:465)
[INFO][Launcher]sam2tsv Exited with failure (-1)
```
It seems the reference fasta has "chrMT" while my bam has "chrM". Because it cannot find chrM in reference fasta, it stopped prematurely after chr9, which is right before chrMT in the fasta file. Sorry that this was the issue and I opened an issue thread for sam2tsv when it is not sam2tsv issue.
(I received these bam files from someone so I didn't do the alignment.) 

Would a possible solution be to replace all "chrMT" in reference fasta file as "chrM"? What do you think?

```
$ cat Sample_A_sam2tsv_tail.txt
e85f63d1-deb4-449c-b5c0-0113b321ccfe	2048	12	chr9	.	.	.	124478033	T	H
e85f63d1-deb4-449c-b5c0-0113b321ccfe	2048	12	chr9	.	.	.	124478034	C	H
e85f63d1-deb4-449c-b5c0-0113b321ccfe	2048	12	chr9	.	.	.	124478035	T	H
e85f63d1-deb4-449c-b5c0-0113b321ccfe	2048	12	chr9	.	.	.	124478036	A	H
e85f63d1-deb4-449c-b5c0-0113b321ccfe	2048	12	chr9	.	.	.	124478037	G	H
e85f63d1-deb4-449c-b5c0-0113b321ccfe	2048	12	chr9	.	.	.	124478038	G	H
e85f63d1-deb4-449c-b5c0-0113b321ccfe	2048	12	chr9	.	.	.	124478039	A	H
e85f63d1-deb4-449c-b5c0-0113b321ccfe	2048	12	chr9	.	.	.	124478040	A	H
e85f63d1-deb4-449c-b5c0-0113b321ccfe	2048	12	chr9	.	.	.	124478041	A	H
e85f63d1-deb4-449c-b5c0-0113b321ccfe	2048	12	chr9	.	.	.	124478042	A	H
```

For picard ValidateSam, I got this standard error:

```
$ cat stderr.validate_sam 
INFO	2020-11-18 19:38:53	ValidateSamFile	

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    ValidateSamFile -I Sample_A.bam -MODE SUMMARY
**********


19:38:53.855 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:bin/picard_java1.8/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Wed Nov 18 19:38:53 EST 2020] ValidateSamFile INPUT=Sample_A.bam MODE=SUMMARY    MAX_OUTPUT=100 IGNORE_WARNINGS=false VALIDATE_INDEX=true INDEX_VALIDATION_STRINGENCY=EXHAUSTIVE IS_BISULFITE_SEQUENCED=false MAX_OPEN_TEMP_FILES=8000 SKIP_MATE_VALIDATION=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Wed Nov 18 19:38:53 EST 2020] Executing as chuk@lt03 on Linux 3.10.0-957.5.1.el7.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_131-b11; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.23.8
WARNING	2020-11-18 19:38:53	ValidateSamFile	NM validation cannot be performed without the reference. All other validations will still occur.
[Wed Nov 18 19:41:18 EST 2020] picard.sam.ValidateSamFile done. Elapsed time: 2.40 minutes.
Runtime.totalMemory()=2075918336
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
```

```
$ cat Sample_A_ValidateSam.txt 


## HISTOGRAM	java.lang.String
Error Type	Count
ERROR:MISSING_READ_GROUP	1
WARNING:RECORD_MISSING_READ_GROUP	1969667
```

I read this warning meant that the header is missing read group information.

```
$ samtools view -H Sample_A.bam
@HD	VN:1.6	SO:coordinate
@SQ	SN:chr1	LN:195471971
@SQ	SN:chr10	LN:130694993
@SQ	SN:chr11	LN:122082543
@SQ	SN:chr12	LN:120129022
@SQ	SN:chr13	LN:120421639
@SQ	SN:chr14	LN:124902244
@SQ	SN:chr15	LN:104043685
@SQ	SN:chr16	LN:98207768
@SQ	SN:chr17	LN:94987271
@SQ	SN:chr18	LN:90702639
@SQ	SN:chr19	LN:61431566
@SQ	SN:chr2	LN:182113224
@SQ	SN:chr3	LN:160039680
@SQ	SN:chr4	LN:156508116
@SQ	SN:chr5	LN:151834684
@SQ	SN:chr6	LN:149736546
@SQ	SN:chr7	LN:145441459
@SQ	SN:chr8	LN:129401213
@SQ	SN:chr9	LN:124595110
@SQ	SN:chrM	LN:16299
@SQ	SN:chrX	LN:171031299
@SQ	SN:chrY	LN:91744698
@SQ	SN:JH584299.1	LN:953012
@SQ	SN:GL456233.1	LN:336933
@SQ	SN:JH584301.1	LN:259875
@SQ	SN:GL456211.1	LN:241735
@SQ	SN:GL456350.1	LN:227966
@SQ	SN:JH584293.1	LN:207968
@SQ	SN:GL456221.1	LN:206961
@SQ	SN:JH584297.1	LN:205776
@SQ	SN:JH584296.1	LN:199368
@SQ	SN:GL456354.1	LN:195993
@SQ	SN:JH584294.1	LN:191905
@SQ	SN:JH584298.1	LN:184189
@SQ	SN:JH584300.1	LN:182347
@SQ	SN:GL456219.1	LN:175968
@SQ	SN:GL456210.1	LN:169725
@SQ	SN:JH584303.1	LN:158099
@SQ	SN:JH584302.1	LN:155838
@SQ	SN:GL456212.1	LN:153618
@SQ	SN:JH584304.1	LN:114452
@SQ	SN:GL456379.1	LN:72385
@SQ	SN:GL456216.1	LN:66673
@SQ	SN:GL456393.1	LN:55711
@SQ	SN:GL456366.1	LN:47073
@SQ	SN:GL456367.1	LN:42057
@SQ	SN:GL456239.1	LN:40056
@SQ	SN:GL456213.1	LN:39340
@SQ	SN:GL456383.1	LN:38659
@SQ	SN:GL456385.1	LN:35240
@SQ	SN:GL456360.1	LN:31704
@SQ	SN:GL456378.1	LN:31602
@SQ	SN:GL456389.1	LN:28772
@SQ	SN:GL456372.1	LN:28664
@SQ	SN:GL456370.1	LN:26764
@SQ	SN:GL456381.1	LN:25871
@SQ	SN:GL456387.1	LN:24685
@SQ	SN:GL456390.1	LN:24668
@SQ	SN:GL456394.1	LN:24323
@SQ	SN:GL456392.1	LN:23629
@SQ	SN:GL456382.1	LN:23158
@SQ	SN:GL456359.1	LN:22974
@SQ	SN:GL456396.1	LN:21240
@SQ	SN:GL456368.1	LN:20208
@SQ	SN:JH584292.1	LN:14945
@SQ	SN:JH584295.1	LN:1976
@PG	ID:minimap2	PN:minimap2
```

Thank you.

**Comment by lindenb** [comment]
> It seems the reference fasta has "chrMT" while my bam has "chrM".

yes , that is the error

**Comment by kac2053** [comment]
I received the bam files from someone. They said they aligned with Mus_musculus.GRCm38.dna.primary_assembly.fa. 

I have GRCm38.primary_assembly.genome.fa but I guess even though they're both GRCm38, they're different?

Thank you very much!
