### ISSUE TITLE
Gtf file with NCBI Ids for backlocate

### ISSUE THREAD

**Issue by pawarad** [lindenb/jvarkit#176]
This is a follow-up question on #170 issue. I am able to operate backlocate successfully after you provided the correct gtf file. Thank you so much for solving the issue promptly. I request you to help me with my following questions.

1) The gtf file contains ensembl IDs. Can you please provide link to a gtf file which contains NCBI Ids? I tried downloading from UCSC browser but that gtf file doesn't work.

2) Do you have command in backlocate where we can provide a list of input instead a single input?
Thank you.

**Comment by lindenb** [comment]
> The gtf file contains ensembl IDs. Can you please provide link to a gtf file which contains NCBI Ids?

no, I don't know such file.

> Do you have command in backlocate where we can provide a list of input instead a single input?

`cat input.txt | java -jar backlocate.jar
`

**Comment by pawarad** [comment]
Thank you @lindenb for your help. I have another question for you. 

### My environment
Linux ISKI0023 3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 01:06:18 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

### Subject of the issue
A month ago, I installed backlocate on my mac which is running smoothly. Now, I am trying to install it on a linux machine but I am getting the following error when I try to git clone the repository.

![Git_error](https://user-images.githubusercontent.com/35432127/107256885-10daf600-6a08-11eb-8b20-b091e8873b03.PNG)

I also tried to download the jvarkit-master file from git and install backlocate but it's not working. I am getting the following error.
![Backlocate_error](https://user-images.githubusercontent.com/35432127/107257222-7202c980-6a08-11eb-990a-7df5499b485a.PNG)

I tried to solve the above error by editing the gradle config file to add the correct JAVA_HOME variable 

`#edited JAVA path`
`JAVA_HOME="/bin/jre1.8.0_91/"`

But it's giving me the following error:

`./gradlew backlocate
Downloading https://services.gradle.org/distributions/gradle-6.7-bin.zip
.........10%..........20%..........30%..........40%..........50%.........60%..........70%..........80%..........90%..........100%
 
Welcome to Gradle 6.7!
 
Here are the highlights of this release:
 - File system watching is ready for production use
 - Declare the version of Java your build requires
 - Java 15 support
 
For more details see https://docs.gradle.org/6.7/release-notes.html
 
Starting a Gradle Daemon (subsequent builds will be faster)
 
> Task :backlocate
fatal: Not a git repository (or any of the parent directories): .git
Downloading https://repo1.maven.org/maven2/com/github/samtools/htsjdk/2.23.0/htsjdk-2.23.0.jar to /programs/ngsprograms/backlocate/jvarkit-master/lib/com/github/samtools/htsjdk/2.23.0/htsjdk-2.23.0.jar
Downloading https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar to /programs/ngsprograms/backlocate/jvarkit-master/lib/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar
Downloading https://repo1.maven.org/maven2/gov/nih/nlm/ncbi/ngs-java/2.9.0/ngs-java-2.9.0.jar to /programs/ngsprograms/backlocate/jvarkit-master/lib/gov/nih/nlm/ncbi/ngs-java/2.9.0/ngs-java-2.9.0.jar
Downloading https://repo1.maven.org/maven2/org/apache/commons/commons-jexl/2.1.1/commons-jexl-2.1.1.jar to /programs/ngsprograms/backlocate/jvarkit-master/lib/org/apache/commons/commons-jexl/2.1.1/commons-jexl-2.1.1.jar
Downloading https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.19/commons-compress-1.19.jar to /programs/ngsprograms/backlocate/jvarkit-master/lib/org/apache/commons/commons-compress/1.19/commons-compress-1.19.jar
Downloading https://repo1.maven.org/maven2/org/tukaani/xz/1.8/xz-1.8.jar to /programs/ngsprograms/backlocate/jvarkit-master/lib/org/tukaani/xz/1.8/xz-1.8.jar
Downloading https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.1.7.3/snappy-java-1.1.7.3.jar to /programs/ngsprograms/backlocate/jvarkit-master/lib/org/xerial/snappy/snappy-java/1.1.7.3/snappy-java-1.1.7.3.jar
Downloading https://repo1.maven.org/maven2/com/beust/jcommander/1.72/jcommander-1.72.jar to /programs/ngsprograms/backlocate/jvarkit-master/lib/com/beust/jcommander/1.72/jcommander-1.72.jar
Downloading https://repo1.maven.org/maven2/org/testng/testng/6.14.3/testng-6.14.3.jar to /programs/ngsprograms/backlocate/jvarkit-master/lib/org/testng/testng/6.14.3/testng-6.14.3.jar
 
[ant:javac] javac: invalid target release: 8
[ant:javac] Usage: javac <options> <source files>
[ant:javac] use -help for a list of possible options
 
> Task :backlocate FAILED
 
FAILURE: Build failed with an exception.
 
* Where:
Build file '/programs/ngsprograms/backlocate/jvarkit-master/build.gradle' line: 675
 
* What went wrong:
Execution failed for backlocate com.github.lindenb.jvarkit.tools.backlocate.BackLocate.
> Compile failed; see the compiler error output for details.
 
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
 
* Get more help at https://help.gradle.org
 
BUILD FAILED in 24s
1 actionable task: 1 executed
(base) [josephv@ISKI0023 jvarkit-master]$ sudo ./gradlew backlocate --info
Native file system watching is not available for this operating system.
net.rubygrapefruit.platform.NativeIntegrationLinkageException: Native library 'libnative-platform-file-events.so' could not be loaded for Linux amd64.
        at net.rubygrapefruit.platform.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:61)
        at net.rubygrapefruit.platform.file.FileEvents.init(FileEvents.java:35)
        at org.gradle.internal.nativeintegration.services.NativeServices.initialize(NativeServices.java:120)
        at org.gradle.internal.nativeintegration.services.NativeServices.initialize(NativeServices.java:84)
        at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:42)
        at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:26)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:41)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:26)
        at org.gradle.launcher.cli.DefaultCommandLineActionFactory$WithLogging.execute(DefaultCommandLineActionFactory.java:240)
        at org.gradle.launcher.Main.doAction(Main.java:35)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:50)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:31)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:35)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
Caused by: java.lang.UnsatisfiedLinkError: /root/.gradle/native/12488b8bf47d2d4c9fbf2f6322a914ad602e24e48041cd04a747c6da556b65c4/linux-amd64/libnative-platform-file-events.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /root/.gradle/native/12488b8bf47d2d4c9fbf2f6322a914ad602e24e48041cd04a747c6da556b65c4/linux-amd64/libnative-platform-file-events.so)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at net.rubygrapefruit.platform.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:51)
        ... 24 more
Initialized native services in: /root/.gradle/native
The client will now receive all logging from the daemon (pid: 66419). The daemon log file: /root/.gradle/daemon/6.7/daemon-66419.out.log
Starting 2nd build in daemon [uptime: 47.6 secs, performance: 98%, non-heap usage: 19% of 268.4 MB]
Using 72 worker leases.
Watching the file system is disabled
Starting Build
Settings evaluated using settings file '/programs/ngsprograms/backlocate/jvarkit-master/settings.gradle'.
Projects loaded. Root project using build file '/programs/ngsprograms/backlocate/jvarkit-master/build.gradle'.
Included projects: [root project 'jvarkit']
 
> Configure project :
Evaluating root project 'jvarkit' using build file '/programs/ngsprograms/backlocate/jvarkit-master/build.gradle'.
All projects evaluated.
Selected primary task 'backlocate' from project :
Tasks to be executed: [backlocate com.github.lindenb.jvarkit.tools.backlocate.BackLocate]
Tasks that were excluded: []
:backlocate (Thread[Execution worker for ':',5,main]) started.
[ant:javac] javac: invalid target release: 8
[ant:javac] Usage: javac <options> <source files>
[ant:javac] use -help for a list of possible options
 
> Task :backlocate FAILED
Starting process 'command 'git''. Working directory: /programs/ngsprograms/backlocate/jvarkit-master Command: git rev-parse --short HEAD
Successfully started process 'command 'git''
fatal: Not a git repository (or any of the parent directories): .git
Caching disabled for backlocate com.github.lindenb.jvarkit.tools.backlocate.BackLocate because:
  Build cache is disabled
Backlocate com.github.lindenb.jvarkit.tools.backlocate.BackLocate is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Starting process 'command 'which''. Working directory: /programs/ngsprograms/backlocate/jvarkit-master Command: which java
Successfully started process 'command 'which''
Starting process 'command 'which''. Working directory: /programs/ngsprograms/backlocate/jvarkit-master Command: which javac
Successfully started process 'command 'which''
Starting process 'command 'which''. Working directory: /programs/ngsprograms/backlocate/jvarkit-master Command: which jar
Successfully started process 'command 'which''
[ant:javac] Compiling 1 source file to /programs/ngsprograms/backlocate/jvarkit-master/tmp
:backlocate (Thread[Execution worker for ':',5,main]) completed. Took 0.291 secs.
 
FAILURE: Build failed with an exception.
 
* Where:
Build file '/programs/ngsprograms/backlocate/jvarkit-master/build.gradle' line: 675
 
* What went wrong:
Execution failed for backlocate com.github.lindenb.jvarkit.tools.backlocate.BackLocate.
> Compile failed; see the compiler error output for details.
 
* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.
 
* Get more help at https://help.gradle.org
 
BUILD FAILED in 1s
1 actionable task: 1 executed`



Can you please help.

**Comment by lindenb** [comment]
see https://stackoverflow.com/a/49206830/58082

**Comment by lindenb** [comment]
`\t` should be tabulations, NOT a litteral `\` followed by `t`... of course...
