### ISSUE TITLE
Cannot use .fna reference file

### ISSUE THREAD

**Issue by togop** [lindenb/jvarkit#181]
### Subject of the issue
Try to run wgscoverageplotter.jar for a .bam file aligned against a reference genome in the .fna file format doesn't work.

### Your environment
* version of jvarkit: cloned repository https://github.com/lindenb/jvarkit on 3 June 2021
* version of java: openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)
* the value of `${JAVA_HOME}`:
* which OS: Ubuntu 18.04.5 LTS

### Steps to reproduce
My command is something like that:
My command is like that:
java -jar /path/to/wgscoverageplotter.jar -dimension 1500x500 -C -1 --clip -R /home/ubuntu/ref_genomes/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna my_minimap2.coordsorted.bam--include-contig-regex "chr(\d+|X|Y|M)$" --percentile median > my_coverage.svg

Reference genome was downloaded form: ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz

returns exception:
[SEVERE][WGSCoveragePlotter]Could not find dictionary next to reference file file:///home/ubuntu/ref_genomes/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna
htsjdk.samtools.SAMException: Could not find dictionary next to reference file file:///home/ubuntu/ref_genomes/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna
        at htsjdk.variant.utils.SAMSequenceDictionaryExtractor$TYPE$1.extractDictionary(SAMSequenceDictionaryExtractor.java:58)
        at htsjdk.variant.utils.SAMSequenceDictionaryExtractor.extractDictionary(SAMSequenceDictionaryExtractor.java:170)
        at com.github.lindenb.jvarkit.util.bio.SequenceDictionaryUtils.extractRequired(SequenceDictionaryUtils.java:178)
        at com.github.lindenb.jvarkit.tools.bam2graphics.WGSCoveragePlotter.doWork(WGSCoveragePlotter.java:289)
        at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMain(Launcher.java:796)
        at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMainWithExit(Launcher.java:959)
        at com.github.lindenb.jvarkit.tools.bam2graphics.WGSCoveragePlotter.main(WGSCoveragePlotter.java:610)
[INFO][Launcher]wgscoverageplotter Exited with failure (-1)

### Expected behaviour
To produce expected plots

### Actual behaviour
Program crash with the above exception

**Comment by lindenb** [comment]
> Could not find dictionary next to reference file file:///home/ubuntu/ref_genomes/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna

as stated in the documentation, the reference must be associated with a *.dict file:

http://lindenb.github.io/jvarkit/WGSCoveragePlotter.html

```
  * -R, --reference
      Indexed fasta Reference file. This file must be indexed with samtools 
      faidx and with picard CreateSequenceDictionary
```

**Comment by togop** [comment]
Thanks, that solved the issue
