### ISSUE TITLE
java.lang.StackOverflowError [Biostar175929]

### ISSUE THREAD

**Issue by vkulaganathan** [lindenb/jvarkit#221]
Am I doing something wrong? I get the following error.

```
$ java -Xms1024m -Xmx8g -jar dist/biostar175929.jar -x 2 -R hg19.p13.plusMT.fa -b rn-3.vcf.gz | more

[INFO][Biostar175929]chrom:chr10 N=254953
[SEVERE][Biostar175929]null
java.lang.StackOverflowError
	at java.base/java.lang.StringCoding.decodeUTF8(StringCoding.java:732)
	at java.base/java.lang.StringCoding.decode(StringCoding.java:257)
	at java.base/java.lang.String.<init>(String.java:507)
	at java.base/java.lang.String.<init>(String.java:561)
	at htsjdk.variant.variantcontext.SimpleAllele.getBaseString(SimpleAllele.java:166)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:229)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
.
.
.
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
	at com.github.lindenb.jvarkit.tools.biostar.Biostar175929.recursive(Biostar175929.java:233)
[INFO][Launcher]biostar175929 Exited with failure (-1)
```

**Comment by lindenb** [comment]
Hi, I think it's because you have too many variants in the VCF. The tool builds a **combination** of all the possible variants in the VCF using a recursive process.

The tool is not dedicated to build all the possible sequences for a large set of variants. You might be interested in GATK https://gatk.broadinstitute.org/hc/en-us/articles/360037594571-FastaAlternateReferenceMaker
