### ISSUE TITLE
BUG:[INFO][Launcher]sam2tsv Exited with failure (-1)

### ISSUE THREAD

**Issue by WXY-Belief** [lindenb/jvarkit#233]
hello, when i run Command-“sam2tsv --reference ${genome_fa} ${i}.sam”，there eixst a bug as follows:

[SEVERE][Sam2Tsv]scan error:
java.lang.IllegalArgumentException: No sequence dictionary in the reference. Use picard CreateSequenceDictionary to index the sequence https://broadinstitute.github.io/picard/command-line-overview.html.
	at com.github.lindenb.jvarkit.util.picard.GenomicSequence.<init>(GenomicSequence.java:141)
	at com.github.lindenb.jvarkit.tools.sam2tsv.Sam2Tsv.printAln(Sam2Tsv.java:339)
	at com.github.lindenb.jvarkit.tools.sam2tsv.Sam2Tsv.scan(Sam2Tsv.java:465)
	at com.github.lindenb.jvarkit.tools.sam2tsv.Sam2Tsv.doWork(Sam2Tsv.java:501)
	at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMain(Launcher.java:1156)
	at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMainWithExit(Launcher.java:1342)
	at com.github.lindenb.jvarkit.tools.sam2tsv.Sam2Tsv.main(Sam2Tsv.java:525)
[SEVERE][Sam2Tsv]No sequence dictionary in the reference. Use picard CreateSequenceDictionary to index the sequence https://broadinstitute.github.io/picard/command-line-overview.html.
java.lang.RuntimeException: No sequence dictionary in the reference. Use picard CreateSequenceDictionary to index the sequence https://broadinstitute.github.io/picard/command-line-overview.html.
	at com.github.lindenb.jvarkit.tools.sam2tsv.Sam2Tsv.scan(Sam2Tsv.java:473)
	at com.github.lindenb.jvarkit.tools.sam2tsv.Sam2Tsv.doWork(Sam2Tsv.java:501)
	at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMain(Launcher.java:1156)
	at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMainWithExit(Launcher.java:1342)
	at com.github.lindenb.jvarkit.tools.sam2tsv.Sam2Tsv.main(Sam2Tsv.java:525)
Caused by: java.lang.IllegalArgumentException: No sequence dictionary in the reference. Use picard CreateSequenceDictionary to index the sequence https://broadinstitute.github.io/picard/command-line-overview.html.
	at com.github.lindenb.jvarkit.util.picard.GenomicSequence.<init>(GenomicSequence.java:141)
	at com.github.lindenb.jvarkit.tools.sam2tsv.Sam2Tsv.printAln(Sam2Tsv.java:339)
	at com.github.lindenb.jvarkit.tools.sam2tsv.Sam2Tsv.scan(Sam2Tsv.java:465)
	... 4 more
[INFO][Launcher]sam2tsv Exited with failure (-1)

**Comment by lindenb** [comment]
There is no sequence dictionary associated to your fasta; Use picard CreateSequenceDictionary to index the sequence https://broadinstitute.github.io/picard/command-line-overview.html
