### ISSUE TITLE
[SEVERE][VcfAncestralAllele]Cannot read non-existent file: ***HELP***

### ISSUE THREAD

**Issue by Warrenkevin** [lindenb/jvarkit#240]
@lindenb Hi Pierre! 

### [SEVERE][VcfAncestralAllele]Cannot read non-existent file:

I keep getting an error message when trying to execute the following code:

java -jar dist/jvarkit.jar vcfancestralalleles \
	-m /usr3/graduate/warrenkb/Candidate_Genes_AA/Manifest_Example_chr15 \
	usr3/graduate/warrenkb/Candidate_Genes_AA/ALDH1A3_37.vcf |\
	bcftools annotate -x '^INFO/AA'

### Your environment

[warrenkb@scc1 jvarkit]$ module load htslib/1.17
[warrenkb@scc1 jvarkit]$ module load samtools/1.17
[warrenkb@scc1 jvarkit]$ module load bcftools/1.17
[warrenkb@scc1 jvarkit]$ module load java/17.0.8
[warrenkb@scc1 jvarkit]$ java -jar dist/jvarkit.jar vcfancestralalleles \
> -m /usr3/graduate/warrenkb/Candidate_Genes_AA/Manifest_Example_chr15 \
> usr3/graduate/warrenkb/Candidate_Genes_AA/ALDH1A3_37.vcf |\
> bcftools annotate -x '^INFO/AA'
[SEVERE][VcfAncestralAllele]Cannot read non-existent file: file:///usr3/graduate/warrenkb/Candidate_Genes_AA/human_ancestor_15.fa
htsjdk.samtools.SAMException: Cannot read non-existent file: file:///usr3/graduate/warrenkb/Candidate_Genes_AA/human_ancestor_15.fa
        at htsjdk.samtools.util.IOUtil.assertFileIsReadable(IOUtil.java:498)
        at com.github.lindenb.jvarkit.tools.onekgenomes.VcfAncestralAllele.loadManifest(VcfAncestralAllele.java:179)
        at com.github.lindenb.jvarkit.tools.onekgenomes.VcfAncestralAllele.beforeVcf(VcfAncestralAllele.java:298)
        at com.github.lindenb.jvarkit.jcommander.OnePassVcfLauncher.doWork(OnePassVcfLauncher.java:123)
        at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMain(Launcher.java:819)
        at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMainWithExit(Launcher.java:982)
        at com.github.lindenb.jvarkit.tools.onekgenomes.VcfAncestralAllele.main(VcfAncestralAllele.java:314)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.github.lindenb.jvarkit.tools.jvarkit.JvarkitCentral$Command.execute(JvarkitCentral.java:276)
        at com.github.lindenb.jvarkit.tools.jvarkit.JvarkitCentral.run(JvarkitCentral.java:749)
        at com.github.lindenb.jvarkit.tools.jvarkit.JvarkitCentral.main(JvarkitCentral.java:760)
[SEVERE][OnePassVcfLauncher]initialization failed
[INFO][Launcher]vcfancestralalleles Exited with failure (-1)
Failed to read from standard input: unknown file type
[warrenkb@scc1 jvarkit]$ 

### Steps to reproduce

/usr3/graduate/warrenkb/Candidate_Genes_AA
$ module load htslib/1.17
$ module load samtools/1.17
$ module load bcftools/1.17
$ module load java/17.0.8
$ git clone "https://github.com/lindenb/jvarkit.git"
$ cd jvarkit
$ ./gradlew jvarkit
$ java -jar dist/jvarkit.jar vcfancestralalleles \
	-m /usr3/graduate/warrenkb/Candidate_Genes_AA/Manifest_Example_chr15 \
	usr3/graduate/warrenkb/Candidate_Genes_AA/ALDH1A3_37.vcf |\
	bcftools annotate -x '^INFO/AA'

### Expected behaviour

Ancestral alleles should be assigned. 

### Actual behavior

Error Message

**Comment by lindenb** [comment]
what is the output of `file /usr3/graduate/warrenkb/Candidate_Genes_AA/human_ancestor_15.fa` ?

**Comment by Warrenkevin** [comment]
@lindenb This is the file I am working with. 

[human_ancestor_15.fa.zip](https://github.com/lindenb/jvarkit/files/13429807/human_ancestor_15.fa.zip)

**Comment by Warrenkevin** [comment]
@lindenb I figured out one problem as far as the manifest, which I think I fixed but there may be something is still wrong. 

**_This I my new error code:_**

[warrenkb@scc1 jvarkit]$ java -jar dist/jvarkit.jar vcfancestralalleles -m /usr3/graduate/warrenkb/Candidate_Genes_AA/Manifest_Example_chr15 usr3/graduate/warrenkb/Candidate_Genes_AA/ALDH1A3_37.vcf |bcftool
s annotate -x '^INFO/AA'
[SEVERE][OnePassVcfLauncher]expected two columns
 * [1]  "15|chr15    ANCESTOR_for_chromosome:GRCh37:15:1:102531392:1  /usr3/graduate/warrenkb/Candidate_Genes_AA/human_ancestor_15.fa"
com.github.lindenb.jvarkit.lang.JvarkitException$TokenErrors: expected two columns
 * [1]  "15|chr15    ANCESTOR_for_chromosome:GRCh37:15:1:102531392:1  /usr3/graduate/warrenkb/Candidate_Genes_AA/human_ancestor_15.fa"
        at com.github.lindenb.jvarkit.tools.onekgenomes.VcfAncestralAllele.loadManifest(VcfAncestralAllele.java:176)
        at com.github.lindenb.jvarkit.tools.onekgenomes.VcfAncestralAllele.beforeVcf(VcfAncestralAllele.java:298)
        at com.github.lindenb.jvarkit.jcommander.OnePassVcfLauncher.doWork(OnePassVcfLauncher.java:123)
        at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMain(Launcher.java:819)
        at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMainWithExit(Launcher.java:982)
        at com.github.lindenb.jvarkit.tools.onekgenomes.VcfAncestralAllele.main(VcfAncestralAllele.java:314)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.github.lindenb.jvarkit.tools.jvarkit.JvarkitCentral$Command.execute(JvarkitCentral.java:276)
        at com.github.lindenb.jvarkit.tools.jvarkit.JvarkitCentral.run(JvarkitCentral.java:749)
        at com.github.lindenb.jvarkit.tools.jvarkit.JvarkitCentral.main(JvarkitCentral.java:760)
[INFO][Launcher]vcfancestralalleles Exited with failure (-1)
Failed to read from standard input: unknown file type
[warrenkb@scc1 jvarkit]$ 


 When I was uploading it to cluster the tabs were some how converted into spaces.

**Comment by lindenb** [comment]
> @lindenb I am not quite sure I know what you mean.. This particular file is human ancestor ancestral condition for chr. 15.

I meant, use the `file` command https://linux.die.net/man/1/file

```
$ file "/usr3/graduate/warrenkb/Candidate_Genes_AA/human_ancestor_15.fa"
```

**Comment by lindenb** [comment]
the chrom15 looks ok.

**Comment by lindenb** [comment]
"15|chr15 ANCESTOR_for_chromosome:GRCh37:15:1:102531392:1 /usr3/graduate/warrenkb/Candidate_Genes_AA/human_ancestor_15.fa"

>  expected two columns

yeah, the message is wrong, it expects 3 columns. I fixed the message today.

I cannot see the content of the file but I'm pretty sure it's not a tab delimited file.

**Comment by Warrenkevin** [comment]
@lindenb This is what my file looks like when it opens. 

<img width="533" alt="Screenshot 2023-11-27 at 11 07 42 AM" src="https://github.com/lindenb/jvarkit/assets/90069270/898ea860-6ba4-41e1-9f31-767ec0a92542">

**Comment by lindenb** [comment]
> , I cannot say anything about it. Just test with the `file` command, convert the tab with `tr`, check by yourself.

**Comment by Warrenkevin** [comment]
@lindenb Hi Pierre, I was able to get working! Thank you for the help.
