### ISSUE TITLE
[SEVERE][MsaToVcf]Duplicate allele added to VariantContext

### ISSUE THREAD

**Issue by liaochen1988** [lindenb/jvarkit#241]
### Subject of the issue
The command I ran was "java -jar ../jvarkit.jar msa2vcf -m bepA_2.txt" and the output error is attached below

[INFO][MsaToVcf]format : Fasta
##fileformat=VCFv4.2
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Approximate read depth (reads with MQ=255 or with bad mates are filtered)">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Approximate read depth; some reads may have been filtered">
##contig=<ID=chrUn,length=753>
##msa2vcf.meta=compilation:20240102101636 githash:717b89405 htsjdk:4.0.1 date:20240105121644 cmd:-m bepA_2.faa
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	PA_1402497_3_DLJEFMPF_03093_	PA_1402507_3_JCNOJIEN_01183_	PA_1402516_3_GEBHJBMB_00757_	PA_1402533_3_JOLDBAAN_01523_	PA_1402547_3_HLGEDPDI_03879_	PA_1402552_3_OCEIHCEE_06036_	PA_1402570_3_EILDPBFJ_00773_	PA_1418247_3_NDPHJBAE_02968_	PA_287_12488_GAHKELMD_02255_	PA_287_12490_NHLAMOGA_00757_	PA_287_12505_CEEHBNPH_02101_	PA_287_12569_HIJPFKFF_02318_	PA_287_12575_NCJEMALD_02311_	PA_287_12577_LLPPMPKN_01995_	PA_287_12642_GAOHHCML_02248_	PA_287_12687_HDFBEIMK_02280_	PA_287_12689_MGPELKNO_03001_	PA_287_12712_KFANAFIM_00320_	PA_287_12720_JOKEPCNB_00319_	PA_287_12726_LBJIDJLF_00661_	PA_287_12781_BHJGJGNJ_02503_	PA_287_12803_NFOBMFKI_01902_	PA_287_12805_NJJDCHFO_01359_	PA_287_12820_MKOJOPOM_03370_	PA_287_12825_GPNNBMKF_05518_	PA_287_12845_FLBEOOJM_00778_	PA_287_12848_MAOHINEJ_00705_	PA_287_2978_KCCGMNJN_01618_	PA_287_3109_HNNBAFAI_03103_	PA_287_3116_LGCKGEML_05873_	PA_287_3130_JLMFAHAL_03074_	PA_287_4055_KDAONLDE_00694_	PA_287_4057_IHJNGGLD_05498_	PA_287_4064_AIEBOCOP_05787_	PA_287_5702_JFPLKAHL_04090_	PA_287_7777_KFGGKOPE_01144_	PA_287_7797_CLHJFHMB_01089_	PA_287_7802_NCKIHPHI_02807_	PA_287_7817_JEJKHOPN_03290_	PA_287_7849_LLMCKINM_01664_	PA_287_7854_JBGLCGLE_01979_	PA_287_7856_EIGEFFIL_02518_	PA_287_7857_MHABBLKI_01150_	PA_287_7860_LFJBACDD_00088_	PA_287_8500_PDJJJGFP_01911_	PA_287_8510_BJCGEBNF_01634_	PA_287_8539_MCAGHFPO_00782_	PA_287_8884_OMHIHELL_01470_
[SEVERE][MsaToVcf]Duplicate allele added to VariantContext: NNNNNNNNNANNNNNNNNAGNCAGNNNNTANNN
java.lang.IllegalArgumentException: Duplicate allele added to VariantContext: NNNNNNNNNANNNNNNNNAGNCAGNNNNTANNN
	at htsjdk.variant.variantcontext.VariantContext.makeAlleles(VariantContext.java:1582)
	at htsjdk.variant.variantcontext.VariantContext.<init>(VariantContext.java:472)
	at htsjdk.variant.variantcontext.VariantContextBuilder.make(VariantContextBuilder.java:647)
	at htsjdk.variant.variantcontext.VariantContextBuilder.make(VariantContextBuilder.java:638)
	at com.github.lindenb.jvarkit.tools.msa2vcf.MsaToVcf.doWork(MsaToVcf.java:617)
	at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMain(Launcher.java:819)
	at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMainWithExit(Launcher.java:982)
	at com.github.lindenb.jvarkit.tools.msa2vcf.MsaToVcf.main(MsaToVcf.java:658)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.github.lindenb.jvarkit.tools.jvarkit.JvarkitCentral$Command.execute(JvarkitCentral.java:281)
	at com.github.lindenb.jvarkit.tools.jvarkit.JvarkitCentral.run(JvarkitCentral.java:759)
	at com.github.lindenb.jvarkit.tools.jvarkit.JvarkitCentral.main(JvarkitCentral.java:770)
[INFO][Launcher]msa2vcf Exited with failure (-1)

### Your environment
* version of jvarkit: 717b89405
* version of java: 20.0.1
* the value of `${JAVA_HOME}`: 
* which OS: Mac OS Ventura 13.6.1

### Steps to reproduce
The command to reproduce the issue was attached above. The file 'bepA_2.txt" is a multiple sequence alignment of protein sequences. I attached the file too (see below). I have to rename it to ".txt" since ".faa" or ".fa" is not a format supported by GitHub.

[bepA_2.txt](https://github.com/lindenb/jvarkit/files/13844916/bepA_2.txt)

### Expected behaviour
I expected it to finish without error.

### Actual behaviour
It reported an error "Duplicate allele added to VariantContext".

**Comment by lindenb** [comment]
These are protein sequences but VCF is only designed for DNA references, NOT amino-acids.
You should use another tool.
