### ISSUE TITLE
unknown error in wgscoverageplotter

### ISSUE THREAD

**Issue by dcopetti** [lindenb/jvarkit#243]
Java version:
openjdk 20-internal 2023-03-21
OpenJDK Runtime Environment (build 20-internal-adhoc..src)
OpenJDK 64-Bit Server VM (build 20-internal-adhoc..src, mixed mode, sharing

### Subject of the issue
per base <=0 with drawing-width

 jvarkit version: 300623ffe
java version: openjdk 20-internal 2023-03-21
* the value of `${JAVA_HOME}`
* which OS

### Steps to reproduce
the command is:
 java -jar /wing2/users/dcopetti/bin/jvarkit.jar wgscoverageplotter --dimension 5000x500 -C -1 --clip --percentile median -o primary_covplot_100k.svg --min-contig-length 100k -R assembly.primary_racon_2.2.2024.fa raw_reads_to_primarys.bam

### Expected behaviour
Run without problems?

### Actual behaviour
the error I get is this:
[SEVERE][WGSCoveragePlotter]pixel per base <=0 with drawing-width:4890.0 distance-between-contigs:1.0 n-chromosomes:5676 genome-length:2688438887
java.lang.IllegalStateException: pixel per base <=0 with drawing-width:4890.0 distance-between-contigs:1.0 n-chromosomes:5676 genome-length:2688438887
        at com.github.lindenb.jvarkit.tools.bam2graphics.WGSCoveragePlotter.doWork(WGSCoveragePlotter.java:358)
        at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMain(Launcher.java:819)
        at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMainWithExit(Launcher.java:982)
        at com.github.lindenb.jvarkit.tools.bam2graphics.WGSCoveragePlotter.main(WGSCoveragePlotter.java:650)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at com.github.lindenb.jvarkit.tools.jvarkit.JvarkitCentral$Command.execute(JvarkitCentral.java:256)
        at com.github.lindenb.jvarkit.tools.jvarkit.JvarkitCentral.run(JvarkitCentral.java:708)
        at com.github.lindenb.jvarkit.tools.jvarkit.JvarkitCentral.main(JvarkitCentral.java:719)
[INFO][Launcher]wgscoverageplotter Exited with failure (-1)

I was able to use this script and these options before with other files, now I can't understand what the error message means. Are there contigs with coverage = 0?
Thanks,
Dario

**Comment by lindenb** [comment]
one contig cannot be displayed because the resulting width will be just too small. Try with a  wider dimension.

**Comment by dcopetti** [comment]
thanks! increasing to 150 or 200 kb resolved the issue
