### ISSUE TITLE
Class file version mismatch error while running Jvarkit

### ISSUE THREAD

**Issue by indianAppl** [lindenb/jvarkit#244]
Hello Pierre,

Thank you for such a wonderful application.  

But whenever I try to run jvarkit, I get the following error:
```

JVARKIT
=======

Author      : Pierre Lindenbaum Phd. Institut du Thorax. Nantes. France.
Exception in thread "main" java.lang.UnsupportedClassVersionError: htsjdk/samtools/util/CloserUtil has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at com.github.lindenb.jvarkit.util.JVarkitVersion.<init>(JVarkitVersion.java:97)
	at com.github.lindenb.jvarkit.util.JVarkitVersion.getInstance(JVarkitVersion.java:129)
	at com.github.lindenb.jvarkit.tools.jvarkit.JvarkitCentral.usageMain(JvarkitCentral.java:344)
	at com.github.lindenb.jvarkit.tools.jvarkit.JvarkitCentral.usage(JvarkitCentral.java:365)
	at com.github.lindenb.jvarkit.tools.jvarkit.JvarkitCentral.run(JvarkitCentral.java:717)
	at com.github.lindenb.jvarkit.tools.jvarkit.JvarkitCentral.main(JvarkitCentral.java:776)

```

As I understand, this has something to do with CloserUtil from samtools. So do I re-install samtools with lower version of Java ? (that would be a nightmare for other pipelines running in my server)...what would your suggestion ?

Regards,
Sangram

**Comment by lindenb** [comment]
> has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

you version of java is just too old. see https://stackoverflow.com/questions/47457105/
