### ISSUE TITLE
bamstats05 error: no stats produced

### ISSUE THREAD

**Issue by Setfelix** [lindenb/jvarkit#54]
Hello,
I am trying to use bamstats05 to produce coverage stats, grouped by gene, for input bam and bed file but have run in to an error. Please help to resolve this.

### My environment
* version of java = 1.8.0_91
* `${JAVA_HOME}` = /usr/lib/jvm/java-8-oracle
*  OS = Ubuntu 14.04 LTS

### Steps to reproduce
My command: java -jar dist/bamstats05.jar \ BEDFILE=~/Documents/wq/exons_bed/wq_intersect_exons_sorted.bed \ IN=~/Documents/wq/revised_target_bams/qiagen/matched_exons_intersect/q_merged.bam

### Actual behaviour
bamstats05 produces the following error:
`[main] ERROR jvarkit - cannot execute command
org.apache.commons.cli.MissingOptionException: Missing required option: B
	at org.apache.commons.cli.DefaultParser.checkRequiredOptions(DefaultParser.java:199)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:130)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:76)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:60)
	at com.github.lindenb.jvarkit.util.command.Command.instanceMainWithExceptions(Command.java:487)
	at com.github.lindenb.jvarkit.util.command.Command.instanceMain(Command.java:586)
	at com.github.lindenb.jvarkit.util.command.Command.instanceMainWithExit(Command.java:592)
	at com.github.lindenb.jvarkit.tools.bamstats04.BamStats05.main(BamStats05.java:332)`

Thanks,
Setor

**Comment by lindenb** [comment]
I didn't remember I wrote this tool :-)

The documentation seems outdated, you should run in like:

```
: java -jar dist/bamstats05.jar -B ~/Documents/wq/exons_bed/wq_intersect_exons_sorted.bed ~/Documents/wq/revised_target_bams/qiagen/matched_exons_intersect/q_merged.bam
```

usage:

```
    -B,--bed <BEDILE>                   bed file (chrom start end GENE)
    -m,--mincoverage <MIN_COVERAGE>      min coverage to say the position is not
                                        covered. default: 0
    -p,--orphan                         use orphan reads (not only properly
                                        paired). default: false
    -q,--minmapq <MMQ>                  min mapping quality. default: 0
```

**Comment by Setfelix** [comment]
Thanks. It worked, using the above syntax, after I merged overlapping intervals in my bed file.
