### ISSUE TITLE
Error when trying to run vcf2sql on the ExAC vcf file

### ISSUE THREAD

**Issue by gilhornung** [lindenb/jvarkit#71]
### Subject of the issue
I am trying to create an sql db from the ExAC vcf file, and getting a "not set as nilleable" error

### Your environment
The command I am using is:
`java -Djvarkit.log.name=vcf2sql -Dfile.encoding=UTF8 -Xmx500m     -cp "/gpfs/apps/el6_x86_64/src/BioApps/jvarkit/jvarkit/lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar:/gpfs/apps/el6_x86_64/src/BioApps/jvarkit/jvarkit/lib/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar:/gpfs/apps/el6_x86_64/src/BioApps/jvarkit/jvarkit/lib/gov/nih/nlm/ncbi/ngs-java/1.2.4/ngs-java-1.2.4.jar:/gpfs/apps/el6_x86_64/src/BioApps/jvarkit/jvarkit/lib/org/apache/commons/commons-compress/1.4.1/commons-compress-1.4.1.jar:/gpfs/apps/el6_x86_64/src/BioApps/jvarkit/jvarkit/lib/org/apache/commons/commons-jexl/2.1.1/commons-jexl-2.1.1.jar:/gpfs/apps/el6_x86_64/src/BioApps/jvarkit/jvarkit/lib/org/tukaani/xz/1.5/xz-1.5.jar:/gpfs/apps/el6_x86_64/src/BioApps/jvarkit/jvarkit/lib/org/xerial/snappy/snappy-java/1.0.3-rc3/snappy-java-1.0.3-rc3.jar:/gpfs/apps/el6_x86_64/src/BioApps/jvarkit/jvarkit/lib/commons-cli/commons-cli/1.3.1/commons-cli-1.3.1.jar:/gpfs/apps/el6_x86_64/src/BioApps/jvarkit/jvarkit/lib/org/slf4j/slf4j-api/1.7.13/slf4j-api-1.7.13.jar:/gpfs/apps/el6_x86_64/src/BioApps/jvarkit/jvarkit/lib/org/slf4j/slf4j-simple/1.7.13/slf4j-simple-1.7.13.jar:/gpfs/apps/el6_x86_64/src/BioApps/jvarkit/jvarkit/dist/vcf2sql.jar" com.github.lindenb.jvarkit.tools.vcf2sql.VcfToSql`

I am using the latest version of vcf2sql (was just installed)

java version:
> java version "1.8.0_91"
> Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
> Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

`${JAVA_HOME}`
> -bash: /usr/local/src/SysTools/Java/jdk1.8.0_91: is a directory

OS is Red Hat Enterprise Linux Server release 6.4 (Santiago)

### Steps to reproduce
I've tried running with the ExAC vcf file. Here are the first 350 lines that I have used as a test:
https://owncloud.incpm.weizmann.ac.il/owncloud/index.php/s/U7zsfWiulaTHJET

### Actual behaviour
I am getting this list of warnings and errors:

> [main] INFO vcf2sql - Starting JOB at Tue Feb 14 12:04:45 IST 2017 com.github.lindenb.jvarkit.tools.vcf2sql.VcfToSql version=393196431631eb57412e990acf780ab68dfde683  built=2017-02-13:17-02-03
> [main] INFO vcf2sql - Command Line args : test.vcf -o test.db
> [main] INFO vcf2sql - Executing as pmgil@isrv02.incpm.weizmann.ac.il on Linux 2.6.32-431.3.1.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_91-b14
> Feb 14, 2017 12:04:45 PM com.github.lindenb.jvarkit.util.vcf.predictions.VepPredictionParser <init>
> WARNING: Undefined VEP tag VARIANT_CLASS
> Feb 14, 2017 12:04:45 PM com.github.lindenb.jvarkit.util.vcf.predictions.VepPredictionParser <init>
> WARNING: Undefined VEP tag MINIMISED
> Feb 14, 2017 12:04:45 PM com.github.lindenb.jvarkit.util.vcf.predictions.VepPredictionParser <init>
> WARNING: Undefined VEP tag TSL
> Feb 14, 2017 12:04:45 PM com.github.lindenb.jvarkit.util.vcf.predictions.VepPredictionParser <init>
> WARNING: Undefined VEP tag SWISSPROT
> Feb 14, 2017 12:04:45 PM com.github.lindenb.jvarkit.util.vcf.predictions.VepPredictionParser <init>
> WARNING: Undefined VEP tag TREMBL
> Feb 14, 2017 12:04:45 PM com.github.lindenb.jvarkit.util.vcf.predictions.VepPredictionParser <init>
> WARNING: Undefined VEP tag UNIPARC
> Feb 14, 2017 12:04:45 PM com.github.lindenb.jvarkit.util.vcf.predictions.VepPredictionParser <init>
> WARNING: Undefined VEP tag HGVS_OFFSET
> Feb 14, 2017 12:04:45 PM com.github.lindenb.jvarkit.util.vcf.predictions.VepPredictionParser <init>
> WARNING: Undefined VEP tag GMAF
> Feb 14, 2017 12:04:45 PM com.github.lindenb.jvarkit.util.vcf.predictions.VepPredictionParser <init>
> WARNING: Undefined VEP tag AFR_MAF
> Feb 14, 2017 12:04:45 PM com.github.lindenb.jvarkit.util.vcf.predictions.VepPredictionParser <init>
> WARNING: Undefined VEP tag AMR_MAF
> Feb 14, 2017 12:04:45 PM com.github.lindenb.jvarkit.util.vcf.predictions.VepPredictionParser <init>
> WARNING: Undefined VEP tag ASN_MAF
> Feb 14, 2017 12:04:45 PM com.github.lindenb.jvarkit.util.vcf.predictions.VepPredictionParser <init>
> WARNING: Undefined VEP tag EAS_MAF
> Feb 14, 2017 12:04:45 PM com.github.lindenb.jvarkit.util.vcf.predictions.VepPredictionParser <init>
> WARNING: Undefined VEP tag EUR_MAF
> Feb 14, 2017 12:04:45 PM com.github.lindenb.jvarkit.util.vcf.predictions.VepPredictionParser <init>
> WARNING: Undefined VEP tag SAS_MAF
> Feb 14, 2017 12:04:45 PM com.github.lindenb.jvarkit.util.vcf.predictions.VepPredictionParser <init>
> WARNING: Undefined VEP tag AA_MAF
> Feb 14, 2017 12:04:45 PM com.github.lindenb.jvarkit.util.vcf.predictions.VepPredictionParser <init>
> WARNING: Undefined VEP tag EA_MAF
> Feb 14, 2017 12:04:45 PM com.github.lindenb.jvarkit.util.vcf.predictions.VepPredictionParser <init>
> WARNING: Undefined VEP tag CLIN_SIG
> Feb 14, 2017 12:04:45 PM com.github.lindenb.jvarkit.util.vcf.predictions.VepPredictionParser <init>
> WARNING: Undefined VEP tag SOMATIC
> Feb 14, 2017 12:04:45 PM com.github.lindenb.jvarkit.util.vcf.predictions.VepPredictionParser <init>
> WARNING: Undefined VEP tag PHENO
> Feb 14, 2017 12:04:45 PM com.github.lindenb.jvarkit.util.vcf.predictions.VepPredictionParser <init>
> WARNING: Undefined VEP tag PUBMED
> Feb 14, 2017 12:04:45 PM com.github.lindenb.jvarkit.util.vcf.predictions.VepPredictionParser <init>
> WARNING: Undefined VEP tag MOTIF_NAME
> Feb 14, 2017 12:04:45 PM com.github.lindenb.jvarkit.util.vcf.predictions.VepPredictionParser <init>
> WARNING: Undefined VEP tag MOTIF_POS
> Feb 14, 2017 12:04:45 PM com.github.lindenb.jvarkit.util.vcf.predictions.VepPredictionParser <init>
> WARNING: Undefined VEP tag HIGH_INF_POS
> Feb 14, 2017 12:04:45 PM com.github.lindenb.jvarkit.util.vcf.predictions.VepPredictionParser <init>
> WARNING: Undefined VEP tag MOTIF_SCORE_CHANGE
> Feb 14, 2017 12:04:45 PM com.github.lindenb.jvarkit.util.vcf.predictions.VepPredictionParser <init>
> WARNING: Undefined VEP tag LoF_info
> Feb 14, 2017 12:04:45 PM com.github.lindenb.jvarkit.util.vcf.predictions.VepPredictionParser <init>
> WARNING: Undefined VEP tag LoF_flags
> Feb 14, 2017 12:04:45 PM com.github.lindenb.jvarkit.util.vcf.predictions.VepPredictionParser <init>
> WARNING: Undefined VEP tag LoF_filter
> Feb 14, 2017 12:04:45 PM com.github.lindenb.jvarkit.util.vcf.predictions.VepPredictionParser <init>
> WARNING: Undefined VEP tag LoF
> Feb 14, 2017 12:04:45 PM com.github.lindenb.jvarkit.util.vcf.predictions.VepPredictionParser <init>
> WARNING: Undefined VEP tag context
> Feb 14, 2017 12:04:45 PM com.github.lindenb.jvarkit.util.vcf.predictions.VepPredictionParser <init>
> WARNING: Undefined VEP tag ancestral
> java.lang.RuntimeException: not set as nilleable
>         at com.github.lindenb.jvarkit.tools.vcf2sql.VcfToSql$Column.escape(VcfToSql.java:196)
>         at com.github.lindenb.jvarkit.tools.vcf2sql.VcfToSql$Table.insert(VcfToSql.java:416)
>         at com.github.lindenb.jvarkit.tools.vcf2sql.VcfToSql.read(VcfToSql.java:664)
>         at com.github.lindenb.jvarkit.tools.vcf2sql.VcfToSql.call(VcfToSql.java:790)
>         at com.github.lindenb.jvarkit.tools.vcf2sql.AbstractVcfToSql.call(AbstractVcfToSql.java:437)
>         at com.github.lindenb.jvarkit.tools.vcf2sql.AbstractVcfToSql.call(AbstractVcfToSql.java:32)
>         at com.github.lindenb.jvarkit.util.command.Command.instanceMainWithExceptions(Command.java:551)
>         at com.github.lindenb.jvarkit.util.command.Command.instanceMain(Command.java:608)
>         at com.github.lindenb.jvarkit.util.command.Command.instanceMainWithExit(Command.java:614)
>         at com.github.lindenb.jvarkit.tools.vcf2sql.VcfToSql.main(VcfToSql.java:813)
> [main] ERROR vcf2sql - not set as nilleable
> [main] ERROR vcf2sql - Command failed
>

**Comment by lindenb** [comment]
Thank you for that report, the problem comes from the exac file, not from my program. The error is generated because there is a FILTER column AC_Adj0_Filter that was not defined in the VCF HEADER of exac. See below: the first line found with this FILTER is a variant, not a VCF header.
```

curl -s  "ftp://ftp.broadinstitute.org/pub/ExAC_release/release0.3.1/ExAC.r0.3.1.sites.vep.vcf.gz" | gunzip -c | grep -m 1 AC_Adj0_Filter | cut -f 1-7
1	13418	.	G	A	510.63	AC_Adj0_Filter

```
